### PR TITLE
Add iOS build of latest iPwnder Lite

### PR DESCRIPTION
**Pull request by UInt2048**
According to both [the depiction](https://web.archive.org/web/20210912112353/https://dora2ios.github.io/info/ipwnderlite/), and the reverse engineered source code, the build of iPwnder Lite is quite out of date ([5th commit on the repo](https://github.com/dora2ios/ipwnder_lite/tree/0f0757c6272050fc36754efc6ed6179a6f39f410) at the latest). This is a problem because the original builds supported only A6(X)/A7 devices.

<details>
<summary>Ghidra Reversed Output of main</summary>

```c

/* WARNING: Unable to use type for symbol payload_path */

int main(int argc,char **argv)

{
  int _int;
  io_client_p *_client;
  undefined *d;
  FILE *fd;
  long payload_len;
  char **_payload_path;
  ulong _payload_len;
  char *path;
  char *url;
  ipwnder_payload_t _payload;
  char *payload_path;
  bool demotionFlag;
  uint id;
  
  if (argc == 1) {
PRINT_USAGE_AND_FAIL:
    _printf("Usage: %s [-p/-d]\n");
    _putchar(10);
    return -1;
  }
  path = argv[1];
  _int = _strcmp(path,"-d");
  if (_int == 0) {
    demotionFlag = true;
  }
  else {
    _int = _strcmp(path,"-p");
    if (_int != 0) goto PRINT_USAGE_AND_FAIL;
    demotionFlag = false;
  }
  _printf("[%s] Waiting for device in DFU mode...\n");
  while (_int = get_device(0x1227,1), _int != 0) {
    _sleep(1);
  }
  _printf("[%s] CONNECTED\n");
  if ((client->hasSerialStr == false) && (read_serial_number(client), client->hasSerialStr != true))
  {
    path = "[%s] ERROR: Serial number was not found!\n";
    goto PRINT_ERROR_AND_FAIL;
  }
  _printf("[%s] CPID: 0x%02x, BDID: 0x%02x, STRG: [%s]\n");
  _client = client;
  if (client->srtg == (char *)0x0) {
    if (client->cpid == 0x8950) {
      path = "[%s] ERROR: Not DFU mode! Already pwned iBSS mode?\n";
    }
    else {
      path = "[%s] ERROR: Not DFU mode!\n";
    }
    goto PRINT_ERROR_AND_FAIL;
  }
  if ((*(byte *)&client->cpfm & 1) == 0) {
    path = "[%s] ERROR: Already have a development device flag!\n";
PRINT_ERROR_AND_SUCCEED:
    _printf(path);
    return 0;
  }
  if (client->hasPwnd != false) {
    _int = _strcmp(client->pwnstr,"demoted");
    if (_int == 0) {
      path = "[%s] ERROR: Already demoted!\n";
    }
    else {
      path = "[%s] ERROR: Already pwned!\n";
    }
    goto PRINT_ERROR_AND_SUCCEED;
  }
  client->isDemotion = demotionFlag;
  if ((demotionFlag) || (id = _client->cpid, id != 0x8955 && id != 0x8950)) goto CALL_CHECKM8_FUNC;
  payload.payload = (byte *)0x0;
  payload._8_8_ = 0;
  payload.path = (char *)0x0;
  if (id == 0x8955) {
    id = _client->bdid;
    if (id == 0) {
      path = "AssetData/boot/Firmware/dfu/iBSS.p101ap.RELEASE.dfu";
      url = 
      "http://appldnld.apple.com/iOS7.1/031-4897.20140627.JCWhk/c0cbed078b561911572a09eba30ea2561cdb efe6.zip"
      ;
      _payload_path = &PTR_s_/tmp/image3/ibss.p101_10000c298;
    }
    else if (id == 4) {
      path = "AssetData/boot/Firmware/dfu/iBSS.p103ap.RELEASE.dfu";
      url = 
      "http://appldnld.apple.com/iOS7.1/031-4897.20140627.JCWhk/238641fd4b8ca2153c9c696328aeeedabede 6174.zip"
      ;
      _payload_path = &PTR_s_/tmp/image3/ibss.p103_10000c2a8;
    }
    else {
      if (id != 2) goto PRINT_UNKNOWN_DEVICE_AND_FAIL;
      path = "AssetData/boot/Firmware/dfu/iBSS.p102ap.RELEASE.dfu";
      url = 
      "http://appldnld.apple.com/iOS7.1/031-4897.20140627.JCWhk/3e0efaf1480c74195e4840509c5806cc83c9 9de2.zip"
      ;
      _payload_path = &PTR_s_/tmp/image3/ibss.p102_10000c2a0;
    }
  }
  else {
    if (id != 0x8950) {
PRINT_UNKNOWN_DEVICE_AND_FAIL:
      path = "[%s] ERROR: Unknown device!\n";
      goto PRINT_ERROR_AND_FAIL;
    }
    id = _client->bdid;
    if ((int)id < 10) {
      if (id == 0) {
        path = "AssetData/boot/Firmware/dfu/iBSS.n41ap.RELEASE.dfu";
        url = 
        "http://appldnld.apple.com/iOS7.1/031-4897.20140627.JCWhk/5ada2e6df3f933abde79738967960a2737 1ce9f3.zip"
        ;
        _payload_path = &PTR_s_/tmp/image3/ibss.n41_10000c278;
      }
      else {
        if (id != 2) goto PRINT_UNKNOWN_DEVICE_AND_FAIL;
        path = "AssetData/boot/Firmware/dfu/iBSS.n42ap.RELEASE.dfu";
        url = 
        "http://appldnld.apple.com/iOS7.1/031-4897.20140627.JCWhk/a05a5e2e6c81df2c0412c51462919860b8 594f75.zip"
        ;
        _payload_path = &PTR_s_/tmp/image3/ibss.n42_10000c280;
      }
    }
    else if (id - 10 < 2) {
      path = "AssetData/boot/Firmware/dfu/iBSS.n48ap.RELEASE.dfu";
      url = 
      "http://appldnld.apple.com/iOS7.1/031-4897.20140627.JCWhk/71ece9ff3c211541c5f2acbc6be7b731d342 e869.zip"
      ;
      _payload_path = &PTR_s_/tmp/image3/ibss.n48_10000c288;
    }
    else {
      if (id != 0xe) goto PRINT_UNKNOWN_DEVICE_AND_FAIL;
      path = "AssetData/boot/Firmware/dfu/iBSS.n49ap.RELEASE.dfu";
      url = 
      "http://appldnld.apple.com/iOS7.1/031-4897.20140627.JCWhk/455309571ffb5ca30c977897d75db77e4407 28c1.zip"
      ;
      _payload_path = &PTR_s_/tmp/image3/ibss.n49_10000c290;
    }
  }
  payload.path = *_payload_path;
  d = (undefined *)_opendir(PTR_s_/tmp/image3/_10000c270);
  if (d == (undefined *)0x0) {
    _printf("[%s] Making directory: %s\n");
    _int = _mkdir(PTR_s_/tmp/image3/_10000c270,0x1ed);
    if (_int != 0) {
      path = "[%s] ERROR: Failed to make dir: %s!\n";
      goto PRINT_ERROR_AND_FAIL;
    }
  }
  fd = _fopen(payload.path,"r");
  payload_path = payload.path;
  if (fd == (FILE *)0x0) {
    _printf("[%s] Downloading image: %s ...\n");
    _int = dl_file(url,path,payload_path);
    if (_int != 0) {
      path = "[%s] ERROR: Failed to get image!\n";
PRINT_ERROR_AND_FAIL:
      _printf(path);
      return -1;
    }
    fd = _fopen(payload.path,"r");
    if (fd == (FILE *)0x0) {
      path = "[%s] ERROR: Failed to open file!\n";
      goto PRINT_ERROR_AND_FAIL;
    }
  }
  _fseek(fd,0,2);
  payload_len = _ftell(fd);
  payload._8_4_ = (int)payload_len;
  _fseek(fd,0,0);
  _payload_len = payload._8_8_ & 0xffffffff;
  payload.payload = (byte *)_malloc(_payload_len);
  if (payload.payload == (byte *)0x0) {
    _printf("[%s] ERROR: Failed to allocating file buffer!\n");
    _fclose(fd);
    return -1;
  }
  _fread(payload.payload,_payload_len,1,fd);
  _fclose(fd);
  _client = client;
CALL_CHECKM8_FUNC:
  id = _client->cpid;
  if (id != 0x8950) {
    if (id == 0x8960) {
      checkm8_s5l8960x();
      return 0;
    }
    if (id != 0x8955) {
      return 0;
    }
  }
  _payload.path = payload.path;
  _payload._8_8_ = payload._8_8_;
  _payload.payload = payload.payload;
  checkm8_s5l8950x(_client,&_payload);
  return 0;
}

```

</details>

I've compiled the latest version with the script I added in UInt2048/ipwnder_lite@70329a40ad52ec33eb82051e0f06005eef3b61ee to potentially alleviate this issue.

NOTE: You may wish to test the DEB before adding to your repo. I tried using an iPad with a USB-C port as the host device, but I wasn't able to succeed. I suspect this issue might be due to the USB-C port, but I don't have a camera adapter on hand to prove it.

NOTE 2: The syntax has changed in this version, the equivalent command to `ipwnder_lite -p` is now `ipwnder_lite -d` (for useful _debug_ output, this was on by default previously)

### CODE REVIEW

**Comment by LukeZGD** [comment]
Nice! I tested it and I can confirm it works. There is 1 (or 2?) thing/s that should be done first for this though:

1. Rebase ipwnder_lite to https://github.com/dora2ios/ipwnder_lite/commit/7265a06d184e433989db640d5e83ea58d5862609 (to auto-send pwned iBSS for A6)
2. Rootless support maybe? idk if it will work there

**Comment by LukeZGD** [comment]
Nice! I tested it and I can confirm it works. There is 1 (or 2/3?) thing/s that should be done first for this though:

1. Rebase ipwnder_lite to https://github.com/dora2ios/ipwnder_lite/commit/7265a06d184e433989db640d5e83ea58d5862609 to auto-send pwned iBSS for A6 (and optionally apply these changes https://github.com/LukeZGD/ipwnder_lite/commit/ba02ebca359ee8dbb040e7550b60930e0de6effc that fixes some return values)
2. Rootless support maybe? idk if it will work there

**Comment by UInt2048** [comment]
@LukeZGD Done. The commit is UInt2048/ipwnder_lite@73578ae6e54323a765c77a3b7f47abfb4fd10f69 if you want to merge it into your fork.

Please test this before merging :)

**Comment by UInt2048** [comment]
@LukeZGD Done. The commit is UInt2048/ipwnder_lite@36289953c86a6cd7f5b0aed6b63c5d586145be8b if you want to merge it into your fork.

Please test this before merging :)

**Comment by LukeZGD** [comment]
Thanks for this, I have tested it and while the root works well as usual, the rootless version gets stuck on a "Found serial number" loop unfortunately. 

From what I have seen, this is an issue with ipwnder_lite itself, and it is something failing on `io_create_plugin_interface`. I might try troubleshooting this later to see exactly what fails here, though idk what can be done (also this was the same issue I had when I tried derootifying the old ipwnder)

I will still go for the merge anyway later I guess, since the issue is only on rootless..

Also I had to edit Releases and add iphoneos-arm64 for the repo to show up on Sileo/Zebra for rootless

**Comment by UInt2048** [comment]
I'm not sure why yet, but this is the same problem as kok3shidoll/ra1npoc#2

**Comment by UInt2048** [comment]
@LukeZGD This is the same problem as kok3shidoll/ra1npoc#2

Looks like it was solved upstream with kok3shidoll/ra1npoc@4f731a94b49abb971341c8fc0d4fec2792277158 so I'll update my build script accordingly

**Comment by UInt2048** [comment]
@LukeZGD Feel free to try it again now.

The commit is UInt2048/ipwnder_lite@aee794f16cc921bf6c4327ece4ea98b633cb7786 now

**Comment by LukeZGD** [comment]
Thanks, tested and it all works now. Merging

**Comment by UInt2048** [comment]
@LukeZGD Glad to hear it works now! 🎉

Don't forget to update the Legacy iOS Kit wiki with the updated device support and rootless support 😜

**Pull request merged**
